version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    reviewers:
      - jamieastley
    assignees:
      - jamieastley
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "Australia/Sydney"