name: Deploy to GitHub Pages

on:
  #  TODO: run on push to master after testing
  pull_request:
    branches:
      - master

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter test

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build Web
        run: flutter build web --release --build-number ${{ github.run_number }} --base-href "/lottie_preview/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
#      name: github-pages TODO: revert later
      name: pull-requests
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4